stages:
  #- build
  - test
  - cleanup

variables:
  GITHUB_REPO: https://github.com/devansh42/momolb.git
  LB_IMAGE_TAG: devansh42/momo




deploy_test_infra: #Deploys DO Infrastructure 
  tags:
    - testing
  stage: test
  script:
    - git clone -b testing $GITHUB_REPO
    - cd momolb 
    - terraform init
    - terraform apply

cleanup_test_infra: #Cleanups DO Infrastructure
  tags:
    - testing
  stage: cleanup
  when: always
  script:
    terraform destroy  


build momo: #Builds Docker image for LB
  tags:
    - testing
  stage: build 
  script: 
    - git clone -b testing $GITHUB_REPO
    - cd momolb
    - docker build -t $LB_IMAGE_TAG .
    - docker push $LB_IMAGE_TAG
