stages:
  - .pre
  - build
  - test
  - cleanup
  - .post

variables:
  GITHUB_REPO: https://github.com/devansh42/momolb.git
  LB_IMAGE_TAG: devansh42/momo




get_repo: #Get the github Repo 
  tags:
    - testing
  stage: .pre
  script:
    - git clone -b testing $GITHUB_REPO
     

deploy_test_infra: #Deploys DO Infrastructure 
  tags:
    - testing
  stage: test
  script: 
    - cd momolb 
    - terraform init
    - terraform apply -auto-approve

cleanup_test_infra: #Cleanups DO Infrastructure
  tags:
    - testing
  stage: cleanup
  when: always
  script:
    - cd momolb 
    - terraform destroy -auto-approve


build momo: #Builds Docker image for LB
  tags:
    - testing
  stage: build 
  script: 
    - cd momolb 
    - docker build -t $LB_IMAGE_TAG .
    - docker push $LB_IMAGE_TAG
