stages:
  - .pre
  - build
  - test
  - cleanup
  - .post

variables:
  GITHUB_REPO: https://github.com/devansh42/momolb.git
  LB_IMAGE_TAG: devansh42/momo
  DIR: momolb


deploy_test_infra: #Deploys DO Infrastructure 
  tags:
    - testing
  stage: test
  before_script:
    - git clone -b testing $GITHUB_REPO && cd $DIR
  script: 
    - terraform init
    - terraform apply -auto-approve

cleanup_test_infra: #Cleanups DO Infrastructure
  tags:
    - testing
  stage: cleanup
  when: always
  before_script:
    - git clone -b testing $GITHUB_REPO && cd $DIR
  script: 
    - terraform destroy -auto-approve


build momo: #Builds Docker image for LB
  tags:
    - testing
  stage: build 

  before_script:
    - git clone -b testing $GITHUB_REPO && cd $DIR
  script: 
    - docker build -t $LB_IMAGE_TAG .
    - docker push $LB_IMAGE_TAG
