stages:
  - .pre
  - build
  - test
  - cleanup
  - .post

variables:
  GITHUB_REPO: https://github.com/devansh42/momolb.git
  RUNNER_REPO: https://github.com/devansh42/momo-runner.git
  LB_IMAGE_TAG: devansh42/momo
  RUNNER_IMAGE_TAG: devansh42/momorunner
  DIR: momolb
  RDIR: momo-runner


deploy_test_infra: #Deploys DO Infrastructure 
  tags:
    - testing
  stage: test
  before_script:
    - git clone -b testing $GITHUB_REPO && cd $DIR
  script: 
    - terraform init
    - terraform apply -auto-approve -lock=false -state-out="/tmp/tfstate"

cleanup_test_infra: #Cleanups DO Infrastructure
  tags:
    - testing
  stage: cleanup
  when: always
  before_script:
    - git clone -b testing $GITHUB_REPO && cd $DIR
  script: 
    - terraform init
    - terraform destroy -auto-approve -lock=false  -state="/tmp/tfstate"


build momo: #Builds Docker image for LB
  tags:
    - testing
  stage: build 

  before_script:
    - git clone -b testing $GITHUB_REPO && cd $DIR
  script: 
    - docker build -t $LB_IMAGE_TAG .
    - docker push $LB_IMAGE_TAG

build runner: #Builds Docker image for Runner
  tags:
    - testing
  stage: build
  before_script:
    - git clone $RUNNER_REPO && cd $RDIR
  script:
    - docker build -t $RUNNER_IMAGE_TAG --build-arg TF_ORG_TOKEN=$K8S_SECRET_TF_ORG_TOKEN .
    - docker push $RUNNER_IMAGE_TAG

